import React, { useRef, useEffect, useState } from 'react'
import hrly from "../../images/hrly.png"
import sy from "../../images/sy.png"




function SmartYield(){
    return (
         
        <div className="images">
            <div className="router-view">
                <div className="container landing-page">
                <div className="row mb-4 mt-2">
                  <div style={{marginTop:"100px"}} className='container col-12 col-xl-4 col-lg-4 col-md-4'>
                      <h1 style={{top: "0px", fontWeight: "750"}}>SMART <span style={{color: "#ff4339"}}>Yield</span><br/> Bonds</h1>
                      <div style={{marginTop:"0px"}} className='graytext'>Solisium SMART is a cross-platform risk management protocol that aims to reduce the risks associated with DeFi. By letting users select a risk profile, Solisium can redistribute risk via tokenized, liquid tranches.
<br/><br/>Solisium's SMART Yield allows users to hedge against interest rate risk in existing DeFi markets.</div>
                      <a style={{marginTop: "20px", padding:"15px 40px"}} className='btn btn-outline-light' href='#'>Under Development</a>
                  </div> 
                  <div className='hideimg container col-12 col-xl-4 col-lg-4 col-md-4'>
                      <img style={{width:"30rem", marginTop:"50px"}} src={sy}/>
                  </div>
                </div>
                <div className="row mb-4 mt-2">
                  <div style={{marginTop:"150px"}} className='hideimg container col-12 col-xl-4 col-lg-4 col-md-4'>
                      
                      <img style={{width:"30rem"}} src={hrly}/>
                  </div>
                  <div style={{marginTop:"100px"}} className='container col-12 col-xl-4 col-lg-4 col-md-4'>
                      <h1 style={{top: "0px", fontSize:"2.5rem"}}>A few words about SMART Yield</h1>
                      <div style={{marginTop:"0px"}} className='graytext'>Our main focus is to implement a variable yield volatility mitigation contract of other projects like the Solisium Swap and more to come, by introducing low and high tranche derivatives.<br/><br/>Holders are able to mint low and high tokens which represent accordingly tranched deposits into the underlying protocol. Low token holders provide the liquidity necessary for the high investors to be able to receive fixed yield. The risk present is that, should the underlying variable rate annuities fall below the level necessary to meet high debt obligations, low yields and potentially even principals would be algorithmically reallocated to cover.<br/><br/>At the same time, low token holders will benefit from the extra yield generated by high investors deposits in cases where the variable rate of the underlying debt pool are higher than the weighted average guaranteed yields of current high investors. It is expected that the junior positions will have more capital in a given pool than the high investors.</div>
                      
                  </div>
                </div>
               
                
              </div>
                







            </div>
            <div>
                <div>
                    
                </div>
            </div>
        </div>
        
    )
}

export default SmartYield